services:
  backend:
    # Use Docker Hub tags for public pushing/pulling via Jenkins
    image: ${DOCKER_USERNAME:-mahadevballa}/stayngo-backend:latest
    container_name: stayngo-backend
    restart: always
    ports:
      - "5001:5001"
    env_file: 
      - .env

  frontend:
    image: ${DOCKER_USERNAME:-mahadevballa}/stayngo-frontend:latest
    container_name: stayngo-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      # Use internal docker networking alias or EC2 public IP
      NEXT_PUBLIC_API_URL: "http://stayngo-backend:5001/api"
    env_file:
      - .env
