sonar.projectKey=StayNGo
sonar.projectName=StayNGo
sonar.projectVersion=1.0

# Define what to analyze
sonar.sources=frontend,backend

# Exclude dependencies and cache from analysis
sonar.exclusions=**/node_modules/**, **/.next/**, **/.venv/**, **/__pycache__/**, **/tests/**

# Local SonarQube server URL
sonar.host.url=http://65.0.117.219:9000
